### ISSUE TITLE
can't differenciate live and static photo

### ISSUE THREAD

**Issue by sunilferry** [DoubangoTelecom/HuaweiFaceLiveness#2]
this sdk is not good for liveness detection because it consider as live image of static photo, you can test it by open an image in other phone show to front of this sdk camera make sure image in 45 degree angle

**Comment by DoubangoTelecom** [comment]
We know it's not good. Contact Huawei to complain. 

https://www.doubango.org/SDKs/face-liveness/docs/Testing_the_competition.html#huawei
